# Generated by Django 4.2.5 on 2023-09-19 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_deletedrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeletedRecord',
        ),
    ]
